window.KAESE_PRODUCTS = [
  {
    "id": "kaese-hombre-003-bermuda-santi",
    "name": "Bermuda Santi",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermudas para Caballeros. Tallas: 28,30,36,38. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-003-bermuda-santi.jpg",
    "imageWidth": 1600,
    "imageHeight": 1130,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 3"
  },
  {
    "id": "kaese-hombre-004-bermuda-fabi",
    "name": "Bermuda Fabi",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermudas para Caballeros. Tallas: 30. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-004-bermuda-fabi.jpg",
    "imageWidth": 1600,
    "imageHeight": 1438,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 4"
  },
  {
    "id": "kaese-hombre-005-bermuda-olise",
    "name": "Bermuda Olise",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermudas para Caballeros. Tallas: 28,30,32,34,36,38. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-005-bermuda-olise.jpg",
    "imageWidth": 1222,
    "imageHeight": 1280,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 5"
  },
  {
    "id": "kaese-hombre-006-bermuda-dylan",
    "name": "Bermuda Dylan",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermudas para Caballeros. Tallas: 28,30,32,34,36,38. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-006-bermuda-dylan.jpg",
    "imageWidth": 1176,
    "imageHeight": 1280,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 6"
  },
  {
    "id": "kaese-hombre-007-bermuda-matias",
    "name": "Bermuda Matias",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermudas para Caballeros. Tallas: 28,30,32,34,36,38. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-007-bermuda-matias.jpg",
    "imageWidth": 1456,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 7"
  },
  {
    "id": "kaese-hombre-008-bermuda-polo",
    "name": "Bermuda Polo",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermudas para Caballeros. Tallas: 28,30,32,34,36,38. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-008-bermuda-polo.jpg",
    "imageWidth": 1146,
    "imageHeight": 1280,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 8"
  },
  {
    "id": "kaese-hombre-010-bermuda-paul",
    "name": "Bermuda Paul",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 65000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermuda Cargo Paul. Tallas: 28,36. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-010-bermuda-paul.jpg",
    "imageWidth": 1600,
    "imageHeight": 1589,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 10"
  },
  {
    "id": "kaese-hombre-012-bermuda-sebas",
    "name": "Bermuda Sebas",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermuda Negra y Humo. C?digo: 004741. Tallas: 30,34. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-012-bermuda-sebas.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 12"
  },
  {
    "id": "kaese-hombre-013-bermuda-sebas-humo",
    "name": "Bermuda Sebas Humo",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 60000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermuda Negra y Humo. C?digo: 004989. Tallas: 30,32,34,36. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-013-bermuda-sebas-humo.jpg",
    "imageWidth": 1361,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 13"
  },
  {
    "id": "kaese-hombre-014-jean-brian",
    "name": "Jean Brian",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 85000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Bermuda Negra y Humo. Talla: 30.34,36. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-014-jean-brian.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 14"
  },
  {
    "id": "kaese-hombre-017-tipo-polo",
    "name": "Tipo Polo",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 35000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Tipo Polo. Talla: S,M,L, XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-017-tipo-polo.jpg",
    "imageWidth": 1599,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 17"
  },
  {
    "id": "kaese-hombre-019-tipo-polo-samuel",
    "name": "Tipo Polo Samuel",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 65000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Tipo Polo. Talla: XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-019-tipo-polo-samuel.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 19"
  },
  {
    "id": "kaese-hombre-020-tipo-polo-cookie",
    "name": "Tipo Polo Cookie",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 50000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Tipo Polo. Talla: M,L, XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-020-tipo-polo-cookie.jpg",
    "imageWidth": 1418,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 20"
  },
  {
    "id": "kaese-hombre-021-camisa-roma",
    "name": "Camisa Roma",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 65000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Tipo Polo. C?digo: 005362. Talla: L, XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-021-camisa-roma.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 21"
  },
  {
    "id": "kaese-hombre-022-tipo-polo-samay",
    "name": "Tipo Polo Samay",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 50000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Tipo Polo. C?digo: 005500. Talla: L, XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-022-tipo-polo-samay.jpg",
    "imageWidth": 1041,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 22"
  },
  {
    "id": "kaese-hombre-023-camisa-burbuja",
    "name": "Camisa Burbuja",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 50000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Tipo Polo. Talla: L,XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-023-camisa-burbuja.jpg",
    "imageWidth": 1024,
    "imageHeight": 1280,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 23"
  },
  {
    "id": "kaese-hombre-026-playeras-003414",
    "name": "Playeras 003414",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 25000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Playeras. C?digo: 003414. Talla: S,M, L, XL. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-026-playeras-003414.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 26"
  },
  {
    "id": "kaese-hombre-029-pantalonetas-tela-algodon-003464",
    "name": "Pantalonetas Tela Algodón 003464",
    "category": "kaese-moda-masculina",
    "categoryLabel": "Moda masculina",
    "price": 30000,
    "detail": "Referencia KAESE Hombre. Colecci?n: Pantalonetas Tela Algodón. C?digo: 003464. Talla: S,L. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-hombre-029-pantalonetas-tela-algodon-003464.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Hombre, pagina 29"
  },
  {
    "id": "kaese-rigido-003-short-viena",
    "name": "Short Viena",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008220. Tallas: 8,10,12. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-003-short-viena.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 3"
  },
  {
    "id": "kaese-rigido-004-short-patricia",
    "name": "Short Patricia",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 009249. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-004-short-patricia.jpg",
    "imageWidth": 1560,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 4"
  },
  {
    "id": "kaese-rigido-005-short-kenia",
    "name": "Short Kenia",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 009289. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-005-short-kenia.jpg",
    "imageWidth": 1132,
    "imageHeight": 1280,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 5"
  },
  {
    "id": "kaese-rigido-006-short-suri",
    "name": "Short Suri",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 009153. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-006-short-suri.png",
    "imageWidth": 1103,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 6"
  },
  {
    "id": "kaese-rigido-007-short-amalia",
    "name": "Short Amalia",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 009095. Tallas: 6,8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-007-short-amalia.png",
    "imageWidth": 1077,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 7"
  },
  {
    "id": "kaese-rigido-008-basico-sin-dobladillo",
    "name": "B?sico Sin Dobladillo",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008220. Tallas: 6,8,10,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-008-basico-sin-dobladillo.png",
    "imageWidth": 1000,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 8"
  },
  {
    "id": "kaese-rigido-009-shorts-con-desgaste",
    "name": "Shorts con Desgaste",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008562. Tallas: 6,8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-009-shorts-con-desgaste.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 9"
  },
  {
    "id": "kaese-rigido-010-short-nora",
    "name": "Short Nora",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 009243. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-010-short-nora.png",
    "imageWidth": 1004,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 10"
  },
  {
    "id": "kaese-rigido-011-short-pink",
    "name": "Short Pink",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 009135. Tallas:6,8,10,12,14.16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-011-short-pink.png",
    "imageWidth": 1023,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 11"
  },
  {
    "id": "kaese-rigido-012-short-dara",
    "name": "Short Dara",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008660. Tallas: 6,8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-012-short-dara.png",
    "imageWidth": 1117,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 12"
  },
  {
    "id": "kaese-rigido-013-short-bianca",
    "name": "Short Bianca",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008598. Tallas: 8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-013-short-bianca.png",
    "imageWidth": 1126,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 13"
  },
  {
    "id": "kaese-rigido-014-short-aurora",
    "name": "Short Aurora",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008562. Tallas: 6,8,10,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-014-short-aurora.png",
    "imageWidth": 1110,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 14"
  },
  {
    "id": "kaese-rigido-015-short-keren",
    "name": "Short Keren",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008749. Tallas: 6,8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-015-short-keren.png",
    "imageWidth": 965,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 15"
  },
  {
    "id": "kaese-rigido-016-short-cristy",
    "name": "Short Cristy",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008986. Tallas: 8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-016-short-cristy.png",
    "imageWidth": 1023,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 16"
  },
  {
    "id": "kaese-rigido-017-short-vivian",
    "name": "Short Vivian",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008968. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-017-short-vivian.png",
    "imageWidth": 1075,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 17"
  },
  {
    "id": "kaese-rigido-018-short-eileen",
    "name": "Short Eileen",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008749. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-018-short-eileen.png",
    "imageWidth": 901,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 18"
  },
  {
    "id": "kaese-rigido-019-short-zoe",
    "name": "Short Zoe",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 007877. Tallas: 8,10,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-019-short-zoe.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 19"
  },
  {
    "id": "kaese-rigido-020-short-candy",
    "name": "Short Candy",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008379. Tallas: 8. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-020-short-candy.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 20"
  },
  {
    "id": "kaese-rigido-021-short-maggy",
    "name": "Short Maggy",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008514. Tallas:6,8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-021-short-maggy.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 21"
  },
  {
    "id": "kaese-rigido-022-short-yareli",
    "name": "Short Yareli",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008672. Tallas,8. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-022-short-yareli.png",
    "imageWidth": 901,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 22"
  },
  {
    "id": "kaese-rigido-023-short-eve",
    "name": "Short Eve",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 53000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Shorts Rigidos Tela Rigida. C?digo: 008672. Tallas: 6,8,10,12,14,16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-023-short-eve.png",
    "imageWidth": 1013,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 23"
  },
  {
    "id": "kaese-rigido-025-short-micaela",
    "name": "Short Micaela",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 58000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 009225. Tallas: 8,10,12,14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-025-short-micaela.png",
    "imageWidth": 1130,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 25"
  },
  {
    "id": "kaese-rigido-026-short-cortado-humo",
    "name": "Short Cortado Humo",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 58000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 008252. Tallas: 6,8,10.12.14.16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-026-short-cortado-humo.png",
    "imageWidth": 1062,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 26"
  },
  {
    "id": "kaese-rigido-027-short-negro-cortado",
    "name": "Short Negro Cortado",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 58000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 008238. Tallas: 6,8,10.12.14.16. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-027-short-negro-cortado.png",
    "imageWidth": 1068,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 27"
  },
  {
    "id": "kaese-rigido-028-short-jaen",
    "name": "Short Jaen",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 58000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 009055. Tallas: 14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-028-short-jaen.png",
    "imageWidth": 1137,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 28"
  },
  {
    "id": "kaese-rigido-029-short-sheila",
    "name": "Short Sheila",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 58000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 004717. Tallas: 8,10.12.14. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-029-short-sheila.png",
    "imageWidth": 1200,
    "imageHeight": 1121,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 29"
  },
  {
    "id": "kaese-rigido-031-short-melisa",
    "name": "Short Melisa",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 33000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 007175. Tallas: 8,10,12. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-031-short-melisa.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 31"
  },
  {
    "id": "kaese-rigido-032-short-ange",
    "name": "Short Ange",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 33000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 007035. Tallas: 8. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-032-short-ange.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 32"
  },
  {
    "id": "kaese-rigido-033-short-alexa",
    "name": "Short Alexa",
    "category": "kaese-moda-femenina",
    "categoryLabel": "Moda femenina",
    "price": 33000,
    "detail": "Referencia KAESE R?gido. Colecci?n: Short Negro y Humo Tela Rigida. C?digo: 006474. Tallas: 8,. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-rigido-033-short-alexa.png",
    "imageWidth": 848,
    "imageHeight": 1200,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE R?gido, pagina 33"
  },
  {
    "id": "kaese-liquidacion-002-vestido-milan",
    "name": "Vestido Milan",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 45000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-002-vestido-milan.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 2"
  },
  {
    "id": "kaese-liquidacion-003-conjunto-malla",
    "name": "Conjunto Malla",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-003-conjunto-malla.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 3"
  },
  {
    "id": "kaese-liquidacion-004-liquidacion-kaese-4",
    "name": "Liquidaci?n KAESE 4",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-004-liquidacion-kaese-4.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 4"
  },
  {
    "id": "kaese-liquidacion-005-deyanira",
    "name": "Deyanira",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 75000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-005-deyanira.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 5"
  },
  {
    "id": "kaese-liquidacion-006-deyanira",
    "name": "Deyanira",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 75000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-006-deyanira.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 6"
  },
  {
    "id": "kaese-liquidacion-007-vestido-lluvia",
    "name": "Vestido Lluvia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-007-vestido-lluvia.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 7"
  },
  {
    "id": "kaese-liquidacion-008-vestido-lluvia",
    "name": "Vestido Lluvia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-008-vestido-lluvia.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 8"
  },
  {
    "id": "kaese-liquidacion-009-liquidacion-kaese-9",
    "name": "Liquidaci?n KAESE 9",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 80000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-009-liquidacion-kaese-9.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 9"
  },
  {
    "id": "kaese-liquidacion-010-liquidacion-kaese-10",
    "name": "Liquidaci?n KAESE 10",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 80000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-010-liquidacion-kaese-10.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 10"
  },
  {
    "id": "kaese-liquidacion-011-liquidacion-kaese-11",
    "name": "Liquidaci?n KAESE 11",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 80000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-011-liquidacion-kaese-11.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 11"
  },
  {
    "id": "kaese-liquidacion-012-flowers",
    "name": "Flowers",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-012-flowers.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 12"
  },
  {
    "id": "kaese-liquidacion-013-flowers",
    "name": "Flowers",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-013-flowers.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 13"
  },
  {
    "id": "kaese-liquidacion-014-flowers",
    "name": "Flowers",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-014-flowers.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 14"
  },
  {
    "id": "kaese-liquidacion-015-flavia",
    "name": "Flavia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-015-flavia.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 15"
  },
  {
    "id": "kaese-liquidacion-016-flavia",
    "name": "Flavia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-016-flavia.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 16"
  },
  {
    "id": "kaese-liquidacion-017-flavia",
    "name": "Flavia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-017-flavia.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 17"
  },
  {
    "id": "kaese-liquidacion-018-conjunto-candy-malla",
    "name": "Conjunto Candy Malla",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 68000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-018-conjunto-candy-malla.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 18"
  },
  {
    "id": "kaese-liquidacion-019-conjunto-malla-candy",
    "name": "Conjunto Malla Candy",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 140000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-019-conjunto-malla-candy.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 19"
  },
  {
    "id": "kaese-liquidacion-020-conjunto-pantalon-malla-rumba",
    "name": "Conjunto Pantalon Malla Rumba",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 125000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-020-conjunto-pantalon-malla-rumba.jpg",
    "imageWidth": 1198,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 20"
  },
  {
    "id": "kaese-liquidacion-021-conjunto-cloock",
    "name": "Conjunto Cloock",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 48000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005645. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-021-conjunto-cloock.jpg",
    "imageWidth": 1169,
    "imageHeight": 1240,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 21"
  },
  {
    "id": "kaese-liquidacion-022-blusa-dayana",
    "name": "Blusa Dayana",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 20000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-022-blusa-dayana.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 22"
  },
  {
    "id": "kaese-liquidacion-023-blusa-alice",
    "name": "Blusa Alice",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 35000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-023-blusa-alice.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 23"
  },
  {
    "id": "kaese-liquidacion-024-camisa-print",
    "name": "Camisa Print",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 38000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005672. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-024-camisa-print.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 24"
  },
  {
    "id": "kaese-liquidacion-025-set-teresa",
    "name": "Set Teresa",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 70000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-025-set-teresa.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 25"
  },
  {
    "id": "kaese-liquidacion-026-set-teresa",
    "name": "Set Teresa",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 70000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-026-set-teresa.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 26"
  },
  {
    "id": "kaese-liquidacion-027-conjunto-massimo",
    "name": "Conjunto Massimo",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005627. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-027-conjunto-massimo.jpg",
    "imageWidth": 1219,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 27"
  },
  {
    "id": "kaese-liquidacion-028-liquidacion-kaese-28",
    "name": "Liquidaci?n KAESE 28",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 75000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-028-liquidacion-kaese-28.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 28"
  },
  {
    "id": "kaese-liquidacion-029-liquidacion-kaese-29",
    "name": "Liquidaci?n KAESE 29",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 75000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-029-liquidacion-kaese-29.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 29"
  },
  {
    "id": "kaese-liquidacion-030-blusa-yarilin",
    "name": "Blusa Yarilin",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 20000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-030-blusa-yarilin.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 30"
  },
  {
    "id": "kaese-liquidacion-031-epoca",
    "name": "Epoca",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 76000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-031-epoca.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 31"
  },
  {
    "id": "kaese-liquidacion-032-epoca",
    "name": "Epoca",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 76000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-032-epoca.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 32"
  },
  {
    "id": "kaese-liquidacion-033-blusa-pasion",
    "name": "Blusa Pasion",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 35000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-033-blusa-pasion.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 33"
  },
  {
    "id": "kaese-liquidacion-034-blusa-pasion",
    "name": "Blusa Pasion",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 35000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-034-blusa-pasion.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 34"
  },
  {
    "id": "kaese-liquidacion-035-blusa-perla",
    "name": "Blusa Perla",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 35000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 006414. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-035-blusa-perla.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 35"
  },
  {
    "id": "kaese-liquidacion-036-enterizo-boho",
    "name": "Enterizo Boho",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 70000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-036-enterizo-boho.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 36"
  },
  {
    "id": "kaese-liquidacion-037-vestido-lia",
    "name": "Vestido Lia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 33000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 004147. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-037-vestido-lia.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 37"
  },
  {
    "id": "kaese-liquidacion-038-set-danny",
    "name": "Set Danny",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 38000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 004377. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-038-set-danny.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 38"
  },
  {
    "id": "kaese-liquidacion-042-conjunto-cristy",
    "name": "Conjunto Cristy",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005645. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-042-conjunto-cristy.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 42"
  },
  {
    "id": "kaese-liquidacion-043-conjunto-pliesse",
    "name": "Conjunto Pliesse",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 49000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005645. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-043-conjunto-pliesse.jpg",
    "imageWidth": 1566,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 43"
  },
  {
    "id": "kaese-liquidacion-044-short-lily",
    "name": "Short Lily",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 28000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005793. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-044-short-lily.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 44"
  },
  {
    "id": "kaese-liquidacion-045-buzo-malla",
    "name": "Buzo Malla",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 20000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005321. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-045-buzo-malla.jpg",
    "imageWidth": 1273,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 45"
  },
  {
    "id": "kaese-liquidacion-046-blusa-malla",
    "name": "Blusa Malla",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 20000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005353. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-046-blusa-malla.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 46"
  },
  {
    "id": "kaese-liquidacion-047-camisa-lola",
    "name": "Camisa Lola",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 25000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 002685. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-047-camisa-lola.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 47"
  },
  {
    "id": "kaese-liquidacion-048-camisa-jezmin",
    "name": "Camisa Jezmin",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 30000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 006127. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-048-camisa-jezmin.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 48"
  },
  {
    "id": "kaese-liquidacion-049-enterizo-abba",
    "name": "Enterizo Abba",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 48000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005077. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-049-enterizo-abba.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 49"
  },
  {
    "id": "kaese-liquidacion-050-camisa-shayla",
    "name": "Camisa Shayla",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 30000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 003578. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-050-camisa-shayla.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 50"
  },
  {
    "id": "kaese-liquidacion-051-conjunto-primavera",
    "name": "Conjunto Primavera",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-051-conjunto-primavera.jpg",
    "imageWidth": 1282,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 51"
  },
  {
    "id": "kaese-liquidacion-052-conjunto-teresa",
    "name": "Conjunto Teresa",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 70000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005796. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-052-conjunto-teresa.jpg",
    "imageWidth": 1240,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 52"
  },
  {
    "id": "kaese-liquidacion-053-conjunto-luxury",
    "name": "Conjunto Luxury",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 60000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005847. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-053-conjunto-luxury.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 53"
  },
  {
    "id": "kaese-liquidacion-054-vestido-aurora",
    "name": "Vestido Aurora",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005793. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-054-vestido-aurora.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 54"
  },
  {
    "id": "kaese-liquidacion-055-set-oriana",
    "name": "Set Oriana",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005800. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-055-set-oriana.jpg",
    "imageWidth": 1229,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 55"
  },
  {
    "id": "kaese-liquidacion-057-conjunto-sharon",
    "name": "Conjunto Sharon",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005942. Talla única. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-057-conjunto-sharon.jpg",
    "imageWidth": 1419,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 57"
  },
  {
    "id": "kaese-liquidacion-058-set-fadua",
    "name": "Set Fadua",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 130000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. C?digo: 005816. TALLA ÚNICA. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-058-set-fadua.jpg",
    "imageWidth": 900,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 58"
  },
  {
    "id": "kaese-liquidacion-059-karito",
    "name": "Karito",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 38000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-059-karito.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 59"
  },
  {
    "id": "kaese-liquidacion-061-ruth",
    "name": "Ruth",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 40000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-061-ruth.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 61"
  },
  {
    "id": "kaese-liquidacion-062-ruth",
    "name": "Ruth",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 40000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-062-ruth.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 62"
  },
  {
    "id": "kaese-liquidacion-063-ruth",
    "name": "Ruth",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 40000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-063-ruth.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 63"
  },
  {
    "id": "kaese-liquidacion-064-julieta",
    "name": "Julieta",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 28000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-064-julieta.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 64"
  },
  {
    "id": "kaese-liquidacion-065-aqua",
    "name": "Aqua",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 70000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-065-aqua.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 65"
  },
  {
    "id": "kaese-liquidacion-066-aqua",
    "name": "Aqua",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 70000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-066-aqua.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 66"
  },
  {
    "id": "kaese-liquidacion-067-atardecer",
    "name": "Atardecer",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-067-atardecer.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 67"
  },
  {
    "id": "kaese-liquidacion-068-regaza",
    "name": "Regaza",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-068-regaza.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 68"
  },
  {
    "id": "kaese-liquidacion-069-regaza",
    "name": "Regaza",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-069-regaza.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 69"
  },
  {
    "id": "kaese-liquidacion-070-regaza",
    "name": "Regaza",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 50000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-070-regaza.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 70"
  },
  {
    "id": "kaese-liquidacion-071-jaguar",
    "name": "Jaguar",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 60000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Talla unica. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-071-jaguar.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 71"
  },
  {
    "id": "kaese-liquidacion-072-jaguar",
    "name": "Jaguar",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 60000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-072-jaguar.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 72"
  },
  {
    "id": "kaese-liquidacion-073-mamona",
    "name": "Mamona",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-073-mamona.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 73"
  },
  {
    "id": "kaese-liquidacion-074-mamona",
    "name": "Mamona",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-074-mamona.jpg",
    "imageWidth": 1068,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 74"
  },
  {
    "id": "kaese-liquidacion-075-tamia",
    "name": "Tamia",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-075-tamia.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 75"
  },
  {
    "id": "kaese-liquidacion-076-viviana",
    "name": "Viviana",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 55000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-076-viviana.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 76"
  },
  {
    "id": "kaese-liquidacion-077-viviana-banana",
    "name": "Viviana Banana",
    "category": "kaese-liquidacion",
    "categoryLabel": "Liquidaci?n",
    "price": 65000,
    "detail": "Referencia KAESE Liquidaci?n. Colecci?n: KAESE Liquidaci?n. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-liquidacion-077-viviana-banana.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Liquidaci?n, pagina 77"
  },
  {
    "id": "kaese-polilicra-004-top-karol",
    "name": "Top Karol",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-004-top-karol.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 4"
  },
  {
    "id": "kaese-polilicra-005-top-grecia",
    "name": "Top Grecia",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-005-top-grecia.svg",
    "imageWidth": 356,
    "imageHeight": 500,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 5"
  },
  {
    "id": "kaese-polilicra-006-top-daniela",
    "name": "Top Daniela",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-006-top-daniela.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 6"
  },
  {
    "id": "kaese-polilicra-007-body-chanel",
    "name": "Body Chanel",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-007-body-chanel.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 7"
  },
  {
    "id": "kaese-polilicra-008-top-paula",
    "name": "Top Paula",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-008-top-paula.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 8"
  },
  {
    "id": "kaese-polilicra-010-lulu-body",
    "name": "Lulu Body",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 35000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-010-lulu-body.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 10"
  },
  {
    "id": "kaese-polilicra-011-isabel-body",
    "name": "Isabel Body",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 35000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-011-isabel-body.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 11"
  },
  {
    "id": "kaese-polilicra-012-cool-body",
    "name": "Cool Body",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-012-cool-body.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 12"
  },
  {
    "id": "kaese-polilicra-013-valery-body",
    "name": "Valery Body",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-013-valery-body.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 13"
  },
  {
    "id": "kaese-polilicra-014-body-danny",
    "name": "Body Danny",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-014-body-danny.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 14"
  },
  {
    "id": "kaese-polilicra-015-body-suiza",
    "name": "Body Suiza",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-015-body-suiza.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 15"
  },
  {
    "id": "kaese-polilicra-016-body-marifer",
    "name": "Body Marifer",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-016-body-marifer.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 16"
  },
  {
    "id": "kaese-polilicra-017-body-basico",
    "name": "Body B?sico",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-005-top-grecia.svg",
    "imageWidth": 356,
    "imageHeight": 500,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 17"
  },
  {
    "id": "kaese-polilicra-018-body-tina",
    "name": "Body Tina",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-018-body-tina.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 18"
  },
  {
    "id": "kaese-polilicra-019-body-candy",
    "name": "Body Candy",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 30000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: KAESE Polilicra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-019-body-candy.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 19"
  },
  {
    "id": "kaese-polilicra-021-body-paty",
    "name": "Body Paty",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 38000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: Body Paty. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-021-body-paty.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 21"
  },
  {
    "id": "kaese-polilicra-022-body-marsella",
    "name": "Body Marsella",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 38000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: Body Paty. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-022-body-marsella.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 22"
  },
  {
    "id": "kaese-polilicra-024-body-camisilla",
    "name": "Body Camisilla",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: Bodys Poli Licra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-024-body-camisilla.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 24"
  },
  {
    "id": "kaese-polilicra-025-picolini",
    "name": "Picolini",
    "category": "kaese-polilicra",
    "categoryLabel": "Polilicra",
    "price": 25000,
    "detail": "Referencia KAESE Polilicra. Colecci?n: Bodys Poli Licra. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-polilicra-005-top-grecia.svg",
    "imageWidth": 356,
    "imageHeight": 500,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE Polilicra, pagina 25"
  },
  {
    "id": "kaese-basicas-003-sueter-oversize-estampado-ref-005825",
    "name": "Su?ter oversize estampado ref. 005825",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. C?digo: 005825. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-003-sueter-oversize-estampado-ref-005825.jpg",
    "imageWidth": 1204,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 3"
  },
  {
    "id": "kaese-basicas-004-sueter-oversize-estampado-ref-005819",
    "name": "Su?ter oversize estampado ref. 005819",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. C?digo: 005819. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-004-sueter-oversize-estampado-ref-005819.jpg",
    "imageWidth": 1332,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 4"
  },
  {
    "id": "kaese-basicas-005-sueter-oversize-estampado-ref-008502",
    "name": "Su?ter oversize estampado ref. 008502",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. C?digo: 008502. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-005-sueter-oversize-estampado-ref-008502.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 5"
  },
  {
    "id": "kaese-basicas-006-sueter-oversize-estampado-ref-008496",
    "name": "Su?ter oversize estampado ref. 008496",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. C?digo: 008496. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-006-sueter-oversize-estampado-ref-008496.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 6"
  },
  {
    "id": "kaese-basicas-007-sueter-oversize-estampado-5",
    "name": "Su?ter oversize estampado 5",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-007-sueter-oversize-estampado-5.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 7"
  },
  {
    "id": "kaese-basicas-008-sueter-oversize-estampado-6",
    "name": "Su?ter oversize estampado 6",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-008-sueter-oversize-estampado-6.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 8"
  },
  {
    "id": "kaese-basicas-009-sueter-oversize-estampado-7",
    "name": "Su?ter oversize estampado 7",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-009-sueter-oversize-estampado-7.jpg",
    "imageWidth": 1199,
    "imageHeight": 1599,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 9"
  },
  {
    "id": "kaese-basicas-010-sueter-oversize-estampado-8",
    "name": "Su?ter oversize estampado 8",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-010-sueter-oversize-estampado-8.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 10"
  },
  {
    "id": "kaese-basicas-011-sueter-oversize-estampado-9",
    "name": "Su?ter oversize estampado 9",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 25000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?teres oversize estampados. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-011-sueter-oversize-estampado-9.jpg",
    "imageWidth": 1200,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 11"
  },
  {
    "id": "kaese-basicas-013-sueter-oversize-tela-pesada",
    "name": "Su?ter oversize tela pesada",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 30000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: Su?ter oversize tela pesada. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-013-sueter-oversize-tela-pesada.jpg",
    "imageWidth": 1086,
    "imageHeight": 1448,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 13"
  },
  {
    "id": "kaese-basicas-016-basico-corto-liso-ref-000818",
    "name": "B?sico corto liso ref. 000818",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 13000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: B?sicos cortos lisos. C?digo: 000818. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-016-basico-corto-liso-ref-000818.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 16"
  },
  {
    "id": "kaese-basicas-017-basico-corto-liso-ref-000818-variante-2",
    "name": "B?sico corto liso ref. 000818 variante 2",
    "category": "kaese-basicas",
    "categoryLabel": "B?sicas y oversize",
    "price": 13000,
    "detail": "Referencia KAESE B?sicas. Colecci?n: B?sicos cortos lisos. C?digo: 000818. Colores, tallas y disponibilidad se confirman por WhatsApp antes de cerrar la compra.",
    "image": "assets/kaese/kaese-basicas-017-basico-corto-liso-ref-000818-variante-2.jpg",
    "imageWidth": 1600,
    "imageHeight": 1600,
    "catalog": "kaese",
    "catalogLabel": "Moda",
    "source": "KAESE B?sicas, pagina 17"
  }
];

